integration/run-integration-tests: make sure the lxc command is available
Signed-off-by: Simon Deziel <simon.deziel@canonical.com>

diff --git a/integration/run-integration-tests b/integration/run-integration-tests
--- a/integration/run-integration-tests
+++ b/integration/run-integration-tests
@@ -9,6 +9,12 @@ sudo apt-get install -y --no-install-recommends \
      python3-dev \
      tox
 
+# Fail if lxc command isn't available
+if ! command -v lxc; then
+    echo "lxc command not available, aborting (hint: snap install lxd)" >&2
+    exit 1
+fi
+
 lxc config set core.trust_password password
 lxc config set core.https_address "[::]"
 
